In [4]:
import nbimporter
from stream_predictions import *

import os
import torch

In [5]:
train = pd.read_csv('csv_files/train.csv')
valid = pd.read_csv('csv_files/valid.csv')
test = pd.read_csv('csv_files/test.csv')

In [6]:
days = ['day_0', 'day_1', 'day_2', 'day_3', 'day_4', 'day_5', 'day_6']

pipelines = [
    (fill_vals, None, {
        'cols': days,
    }),  
    (add_pct_change, None, None),
    (log_transform, 
        ['day_0', 'day_1', 'day_2', 'day_3', 'day_4', 'day_5', 'day_6', 'days_since_release', 'Next Full Week Streams'], 
        {'prediction_col': 'Next Full Week Streams'}
    )
]

X_train, Y_train = feature_engine_pipe(train, pipelines, 'log Next Full Week Streams')
X_valid, Y_valid = feature_engine_pipe(valid, pipelines, 'log Next Full Week Streams')

In [7]:
X_train

popularity  log days_since_release  log day_0  log day_1  log day_2  \
0             38.0                5.164786   7.033506   7.018402   7.090077   
1             38.0                7.504392   7.467942   7.483244   7.647786   
2             44.0                8.613230   8.937875   8.909235   8.873608   
3              1.0                6.563856  12.521438  12.553725  12.605238   
4             15.0                7.544332  11.127498  11.142789  11.219131   
...            ...                     ...        ...        ...        ...   
141324        56.0                9.077951   7.792349   7.768533   7.734996   
141325        29.0                7.783641   7.629490   7.643962   7.678789   
141326        29.0                7.610853   7.542744   7.434848   7.351800   
141327        23.0                8.071531   9.346443   9.321166   9.257606   
141328        30.0                8.097426   7.382746   7.394493   7.244228   

        log day_3  log day_4  log day_5  log day_6  1_day_%_change  \
0        7.098376   6.820016   7.146772   7.263330        1.521934   
1        7.407318   7.319202   7.406711   7.477604       -1.518560   
2        8.859221   8.688454   8.842316   8.979669        2.905405   
3       12.615679  12.469947  12.774733  13.063537       -3.177137   
4       11.129657  10.912193  11.148909  11.270714       -1.517433   
...           ...        ...        ...        ...             ...   
141324   7.734121   7.619724   7.720905   7.764296        2.410148   
141325   7.612831   7.397562   7.620215   7.727976       -1.436782   
141326   7.382124   7.155396   7.311218   7.394493       11.393152   
141327   9.257606   9.257606   9.257606   9.257606        2.559971   
141328   7.160846   7.028201   7.271704   7.393263       -1.167793   

        3_day_%_change  6_day_%_change  
0            -6.280992      -20.532586  
1             6.250000       -0.961538  
2             8.182981       -4.093199  
3            -8.993676      -41.847338  
4            -0.215660      -13.343271  
...                ...             ...  
141324        5.995624        2.845011  
141325        1.679842       -9.379128  
141326       17.423771       15.980332  
141327        9.290347        9.290347  
141328       24.844720       -1.046154  

[141329 rows x 12 columns]

In [17]:
arr = [1, 2, 3, 4]
x_data = torch.tensor(data)
x_data

tensor([1, 2, 3, 4])

In [15]:
np_arr = np.array([[4, 5], [6, 7]])
np_data = torch.from_numpy(np_arr)
np_data

tensor([[4, 5],
        [6, 7]])

In [19]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([1, 1, 1, 1])

In [20]:
np_ones = torch.ones_like(np_data)
np_ones

tensor([[1, 1],
        [1, 1]])

In [41]:
print(torch.rand(3, 4))

shape = (3, 4,)

rand_tens = torch.rand(shape)

tensor([[0.9124, 0.8098, 0.3419, 0.9915],
        [0.5162, 0.9887, 0.0942, 0.7331],
        [0.9284, 0.8580, 0.8459, 0.7059]])


In [48]:
zero = torch.tensor([1])

print(torch.is_nonzero(zero))

full_tens = torch.full(size=(2, 2,), fill_value=100)
full_tens

True


tensor([[100, 100],
        [100, 100]])

In [50]:
torch.adjoint(np_data)

tensor([[4, 6],
        [5, 7]])

In [61]:
x = torch.ones(5, 3)
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
index = torch.tensor([0, 4, 2])
x.index_add_(0, index, t)

tensor([[ 2.,  3.,  4.],
        [ 1.,  1.,  1.],
        [ 8.,  9., 10.],
        [ 1.,  1.,  1.],
        [ 5.,  6.,  7.]])

In [69]:
torch.cuda.is_available()

False